name: Client Update Notification

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
name: Run simple notification
      run: echo "CLIENT UPDATED. Notification executed successfully."
